enable-messages-user: true
enable-messages-owner: false
enable-messages-admin: true
enable-messages-error: true
enable-messages-help: true
explosion-protection-all: false
enable-chest-rotation: false
enable-permissions: true
enable-protection-doors: true
enable-protection-trapdoors: true
allow-admin-snoop: true
allow-admin-bypass: true
allow-admin-break: true
enable-quick-protect: true
enable-color-tags: true
default-door-timer: 0
broadcast-snoop-target: '[Operators]'
broadcast-break-target: '[Operators]'
broadcast-reload-target: '[Operators]'
strings-file-name: strings-en.yml
