tools:
  tool:
    defaultEnabled: false
    mode: LOOKUP
    aliases:
    - t
    params: area 0 all sum none limit 15 desc silent
    leftClickBehavior: NONE
    item: 270
    rightClickBehavior: TOOL
    permissionDefault: 'TRUE'
    canDrop: true
  toolblock:
    params: area 0 all sum none limit 15 desc silent
    permissionDefault: 'TRUE'
    rightClickBehavior: BLOCK
    item: 7
    mode: LOOKUP
    canDrop: false
    defaultEnabled: true
    aliases:
    - tb
    leftClickBehavior: TOOL
mysql:
  user: root
  port: 3306
  password: onetwothreefourfive6789tEn
  host: localhost
  database: champcraft
logging:
  hiddenBlocks:
  - 0
  logCreeperExplosionsAsPlayerWhoTriggeredThese: false
  logPlayerInfo: false
  hiddenPlayers: []
  logKillsLevel: PLAYERS
consumer:
  timePerRun: 200
  useBukkitScheduler: true
  forceToProcessAtLeast: 20
  delayBetweenRuns: 6
lookup:
  linesLimit: 1500
  defaultTime: 30 minutes
  defaultDist: 20
  linesPerPage: 15
questioner:
  askClearLogs: true
  banPermission: mcbans.ban.local
  askRollbacks: true
  askRedos: true
  askClearLogAfterRollback: true
  askRollbackAfterBan: false
updater:
  checkVersion: true
loggedWorlds:
- world
clearlog:
  enableAutoClearLog: false
  auto:
  - world "world" before 365 days all
  - world "world" player lavaflow waterflow leavesdecay before 7 days all
  - world world_nether before 365 days all
  - world world_nether player lavaflow before 7 days all
  autoClearLogDelay: 6h
  dumpDeletedLog: false
rollback:
  replaceAnyway:
  - 8
  - 9
  - 10
  - 11
  - 51
  maxArea: 50
  dontRollback:
  - 10
  - 11
  - 46
  - 51
  maxTime: 2 days
version: '1.52'
